
let suma = 2 + 2;
console.log( suma );
let resta = 4 - 2;
console.log( resta );
let multiplicacion = 5 * 10;
console.log( multiplicacion );
let division = 4 / 2;
console.log( division );
let percentage = 4 % 100;
console.log( percentage );
let completo = ((( 2 + 2 ) - ( 5 * 50)) / 10) % 100;
console.log( completo );
let noTypesElements = (2+2) - (8*5) + "pepe";
console.log( noTypesElements );
let noTypesElementsTwo = "pepe" + (5 * 10) ;
console.log( noTypesElementsTwo );
let noTypesElementsThree = "pepe" + 4 + 10 ;
console.log( noTypesElementsThree );
let noTypesElementsFour = 4 + 10 + "pepe";
console.log( noTypesElementsThree );